const data = [
  {
    id: 1,
    image: "/assets/projects__images/java-script.png",
    title: "API - JavaScript",
    description: "API realizada para a administração de um aplicativo de academia.",
    technologies: "JavaScript / Node.JS / SQLite / Express / JSON Web Token ",
    githubLink: "https://github.com/lucasrp98/api-treinow",
  },
  {
    id: 2,
    image: "/assets/projects__images/java.png",
    title: "API - Java",
    description: "API realizada para um site de gestão de pessoas. ",
    technologies: "Java / Spring Boot",
    githubLink: "https://github.com/lucasrp98/gestao-pessoas",
  },
  {
    id: 3,
    image: "/assets/projects__images/php.png",
    title: "API - PHP",
    description: "API para ser utilizada em futuro aplicativo. ",
    technologies: "PHP",
    githubLink: "https://github.com/lucasrp98/trabalho_webII",
  },
  {
    id: 4,
    image: "/assets/projects__images/pokemon-vector-logo.png",
    title: "Pokemon - APP",
    description: " Esse projeto foi utilizado para demonstrar os meus conhecimentos no consumo de API's e construir minhas tela a partir do consumo da API do Pokemon.",
    technologies: "Flutter / DIO ",
    githubLink: "https://github.com/lucasrp98/pokemon-app",
  },
  {
    id: 5,
    image: "/assets/projects__images/random_user.png",
    title: "Random User - APP",
    description: " Esse projeto foi utilizado para demonstrar os meus conhecimentos no consumo de API's e construir minhas tela a partir do consumo da API RANDOM USER GENERATOR.",
    technologies: "Flutter / HTTP ",
    githubLink: "https://github.com/lucasrp98/random_user",
  },
  {
    id: 6,
    image: "/assets/projects__images/politiza.png",
    title: "Politiza",
    description: " Esse projeto foi utilizado no desenvolvimento do meu trabalho de conclusão da faculdade, no qual foi desenvolvido o protótipo de um aplicativo que tem o objetivo de auxiliar os cidadãos da cidade de Camaquã-RS a registrarem os incidentes que ocorrem na sua Comunidade ao poder público, com a intenção de que os mesmos coletem os dados desses incidentes e elaborem um plano de ação para a resolução desses incidentes.! ",
    technologies: " Flutter / SQLite ",
    githubLink: "https://github.com/lucasrp98/politiza",
  },
  {
    id: 7,
    image: "/assets/projects__images/rbn-stress.png",
    title: "Work Stress",
    description: " Um projeto de um site que visa auxiliar os colaboradores da empresa a realizarem exercicíos físicos durante o horário de trabalho, com a intenção de aliviar o stress diário e melhorar a produção dos mesmos!",
    technologies: " TypeScript / React / CSS / Next.JS ",
    githubLink: "https://github.com/lucasrp98/rbn_stress",
  },
  {
    id: 8,
    image: "/assets/projects__images/nutads.png",
    title: "NuTads",
    description: " Esse projeto foi realizado em dupla e tinha objetivo de ser uma réplica do aplicativo NuBank, mas com uma versão para Desktop. Além disso, consegue-se realizar a persistência de alguns dados do programa!",
    technologies: " Java ",
    githubLink: "https://github.com/lucasrp98/NuTads",
  },
  {
    id: 9,
    image: "/assets/projects__images/logo.png",
    title: "Blog",
    description: " Esse projeto foi realizado para demonstrar os meus conhecimentos como Full-Stack, no qual criei uma API e consumi os seus dados no Front-End.",
    technologies: "JavaScript / Node.JS / SQLite / Express / JSON Web Token ",
    githubLink: "https://github.com/lucasrp98/blog",
  },
];

export default data;
